# Generated by Django 4.2.7 on 2023-11-29 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["email"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
